<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php //TODO add a form to add data here, currently only on Adyen. ?>
<?php $_code = $this->getMethodCode(); ?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">

        <?php if($this->genderShow()):?>
        <li><label for="gender" class="required"><em>*</em><?php echo $this->__('Gender') ?></label>
            <div class="input-box">
                <select id="gender" name="payment[gender]" title="<?php echo $this->__('Gender') ?>" class="validate-select">
                    <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions();?>
                    <?php $value = $this->getGender();?>
                    <?php foreach ($options as $option):?>
                        <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $value) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </li>
        <?php endif; ?>

        <?php if($this->dobShow()):?>
        <li>
            <label for="month" class="required"><em>*</em><?php echo $this->__('Date of Birth') ?></label>
            <div class="input-box customer-dob">
                <?php
                $this->setDateInput('d',
                    '<div class="dob-day">
                         <input type="text" id="day" name="day" value="' . $this->getDay() . '" title="' . $this->__('Day') . '" class="input-text validate-custom" />
             <label for="' . $this->getFieldId('day') . '">' . $this->__('DD') . '</label>
         </div>'
                );

                $this->setDateInput('m',
                    '<div class="dob-month">
                         <input type="text" id="month" name="' . $this->getFieldName('month') . '" value="' . $this->getMonth()  . '" title="' . $this->__('Month')  . '" class="input-text validate-custom" ' . $this->getFieldParams()  . ' />
             <label for="' . $this->getFieldId('month') . '">' . $this->__('MM')  . '</label>
         </div>'
                );

                $this->setDateInput('y',
                    '<div class="dob-year">
                         <input type="text" id="year" name="' . $this->getFieldName('year') . '" value="' . $this->getYear()  . '" title="' . $this->__('Year')  . '" class="input-text validate-custom" ' . $this->getFieldParams()  . ' />
             <label for="' . $this->getFieldId('year') . '">' . $this->__('YYYY')  . '</label>
         </div>'
                );
                ?>
                <?php echo $this->getSortedDateInputs() ?>
                <div class="dob-full" style="display:none;">
                    <input type="hidden" id="dob" name="payment[dob]" />
                </div>

                <div class="validation-advice" style="display:none;"></div>
            </div>
            <script type="text/javascript">
                //<![CDATA[
                var customer_dob = new Varien.DOB('.customer-dob', true, '<?php echo $this->getDateFormat() ?>');
                //]]>
            </script>
        </li>
        <?php endif; ?>

        <li>
            <?php echo $this->__('You will be redirected to Adyen website when you place an order.') ?>
        </li>
    </ul>
</fieldset>
<div>
    <span id="ipayment-elv-please-wait" style="display:none;" class="opc-please-wait">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/> &nbsp; <?php echo $this->__('Submitting payment information...') ?> &nbsp;
    </span>
</div>

