<?php

/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php if($this->hasExpressCheckout() || $this->hasCashExpressCheckout() ): ?>

<div id="adyen-checkout-wrapper">
    <form action="<?php echo  $this->getUrl("adyen/checkoutPos", array('_secure'=>true)); ?>" method="post">
        <input style="width:250px;" type="text" class="input-text" name="adyenPosEmail" id="adyenPosEmail" value="" size="60"  placeholder="Email" autocapitalize="off"/>

        <?php if($this->hasExpressCheckout()): ?>
            <button id="CheckoutWithPos" style="" type="submit" title="Checkout with POS" class="button btn-proceed-checkout btn-checkout adyen-checkout-button">
                <span><span>Checkout with POS</span></span>
            </button>
        <?php endif; ?>

    </form>

    <form action="<?php echo  $this->getUrl("adyen/checkoutCash", array('_secure'=>true)); ?>" method="post">
        <?php if($this->hasCashExpressCheckout()): ?>
            <button id="CheckoutWithCash" style="" type="submit" title="Checkout with Cash" class="button btn-proceed-checkout btn-checkout adyen-checkout-button">
                <span><span>Checkout with Cash</span></span>
            </button>
        <?php endif; ?>
    </form>
</div>

<div>-OR-</div>

<?php endif; ?>