
<?php if($this->hasEnableScanner()): ?>
<div id="adyenCustomScanWrapper">
    <form id="addToCartBarCode" method='post' action="<?php echo  $this->getUrl("adyen/updateCart/index"); ?>">

        <h3>Barcode scanner</h3>

        <div id="scan">
            <input type="text" class="input-text" name="code" id="inpscan" value="" size="60"  placeholder="Scan barcode with scanner" autofocus/>
        </div>

        <div id="customscan" style="display:none;">
            <input type="text" class="input-text" name="customcode" id="inpcustomscan" value="" size="60"  placeholder="Fil in custom barcode">
            <button id="SubmitCustomScan" type="button" title="Submit" class="button btn-proceed-checkout btn-checkout">
                <span><span>Add</span></span>
            </button>
        </div>

        <br />
        <button id="StopCustomScan" type="button" title="Custom barcode" class="button btn-proceed-checkout btn-checkout">
            <span><span>Custom barcode</span></span>
        </button>

        <button id="StartScan" style="display:none; margin:0;" type="button" title="Start Auto Scanning" class="button btn-proceed-checkout btn-checkout">
            <span><span>Start Auto Scanning</span></span>
        </button>

    </form>


    <script type="text/javascript">


        var intervalId;
        var scanInProgress = false;

        // show autostart button for IOS because they block the onload focus event
        var iOS = ( navigator.userAgent.match(/(iPad|iPhone|iPod)/g) ? true : false );
        if(iOS) {
            // show auto startscan buttton
            $('StartScan').show();
        }

        $('inpscan').observe('focus', function(e){
            $('StartScan').hide();
            intervalId = setInterval('scan()', 250);
        });

        $('inpscan').observe('blur', function(e){

            clearInterval(intervalId);
            $('StartScan').show();
        });

        $('StartScan').observe('click', function(e){

            $('scan').show();
            $('customscan').hide();

            $('StopCustomScan').show();

            $('inpscan').focus();
            intervalId = setInterval('scan()', 250);
            $('StartScan').hide();

        });

        $('StopCustomScan').observe('click', function(e){
            $('scan').hide();
            $('customscan').show();
            $('inpcustomscan').focus();
            $('StopCustomScan').hide();
            $('StartScan').show();

        });

        $('SubmitCustomScan').observe('click', function(e){
            var value =  $('inpcustomscan').value;;
            ajaxCall(value);
            $('inpcustomscan').value = "";
            $('inpcustomscan').focus();
            e.preventDefault();
        });



        // check if scan is done with scanning
        function checkValueInput(value) {

            var currentValue = $('inpscan').value;

            if(value == currentValue) {
                // DO ajax call
                ajaxCall(value);
                $('inpscan').value = "";
                this.scanInProgress = false;
                return;
            }

            // call same function after certain period of time
            var test = setTimeout("checkValueInput($('inpscan').value)", 100);
        }


        function scan() {

            if(this.scanInProgress === false) {

                // get value
                var value = $('inpscan').value;
                if(value) {
                    this.scanInProgress = true;

                    // extra check for full input from scanner
                    setTimeout("checkValueInput($('inpscan').value)", 250);
                }
            }
        }

        function ajaxCall(code) {

            var form = document.getElementById("addToCartBarCode");
            new Ajax.Request(form.action, {
                parameters: {code: code, isAjax: 1, method: 'POST'},
                onSuccess: function(transport) {

                    var response = transport.responseText;
                    // update
                    $$('.col-main').each(
                        function (e) {
                            e.update(response);
                        }
                    );
                },
                onFailure: function(){
                    alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>');
                }
            });

        }
    </script>
</div>
<?php endif; ?>