<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php
/**
 * One page checkout payment methods
 *
 * @see Mage_Checkout_Block_Onepage_Payment_Methods
 */
?>


<?php
$methods = $this->getMethods();
$oneMethod = count($methods) <= 1;


$helper = Mage::helper('onestepcheckout/checkout');
$hide_nonfree_methods = false;
if($helper->settings['hide_nonfree_payment_methods'])   {
    foreach($this->getMethods() as $_method)    {
        if($_method->getCode() == 'free')   {
            $hide_nonfree_methods = true;
        }
    }
}


?>

<div class="payment-methods">
    <script type="text/javascript">
        //<![CDATA[
        <?php echo $this->getChildHtml('reward.scripts'); ?>
        <?php echo $this->getChildHtml('customerbalance_scripts'); ?>
        var payment = new Payment('checkout-payment-method-load', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
        payment.currentMethod = "<?php echo $this->getQuote()->getPayment()->getMethod() ?>";
        //]]>
    </script>
    <?php if(Mage::helper('onestepcheckout')->isEnterprise()):?>
        <?php echo $this->getChildHtml('customerbalance'); ?>
        <?php echo $this->getChildHtml('reward.points'); ?>
    <?php endif;?>

    <?php if (count($this->getMethods())=='1' && Mage::getStoreConfig('onestepcheckout/general/hide_payment_method')):?>
        <dl id="checkout-payment-method-load" style="display: none">
            <?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>

                <dt>
                    <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="hidden" name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" class="radio" <?php if($this->getSelectedMethodCode()==$_code || ($hide_nonfree_methods && $_code == 'free')): ?> checked="checked"<?php endif; ?> />
                    <label for="p_method_<?php echo $_code ?>"><?php echo $_method->getTitle() ?></label></dt>
            <?php endforeach; ?>
        </dl>
    <?php else:?>

        <dl id="checkout-payment-method-load">
            <?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
                <?php if($hide_nonfree_methods && $_code != 'free') continue;

                $_style = "";
                if($_code == "adyen_hpp") {
                    // get method and check if config payment/adyen_hpp/disable_hpptypes is set
                    $disabled = $_method->getHppOptionsDisabled();
                    if(!$disabled) {
                        $_style = ($_code == "adyen_hpp" && !$oneMethod) ? "display:none" : "";
                    }
                } else if ($_code == "adyen_oneclick" && !$oneMethod) {
                    $_style = "display:none";
                }
                ?>

                <dt style="<?php echo $_style; ?>">
                    <?php if( sizeof($this->getMethods()) > 1 ): ?>
                        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" class="radio validate-one-required-by-name" <?php if($this->getSelectedMethodCode()==$_code || ($hide_nonfree_methods && $_code == 'free')): ?> checked="checked"<?php endif; ?> />
                    <?php else: ?>
                        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" /></span>
                    <?php endif; ?>
                    <label for="p_method_<?php echo $_code ?>"><?php echo $_method->getTitle() ?></label>
                </dt>
            <?php if($html = $this->getChildHtml('payment.method.'.$_code)): ?>
            <?php $class = ($_code == "adyen_hpp" || $_code == "adyen_oneclick") ? "" :  "payment-method"; ?>
                <dd id="container_payment_method_<?php echo $_code; ?>" class="<?php echo $class; ?>">
                    <?php echo $html; ?>
                </dd>
            <?php endif; ?>
                <script type="text/javascript">
                    //<![CDATA[

                    var SwitchMethod= function() {
                        var method = $('p_method_<?php echo $_code?>').value;

                        if(method != "adyen_hpp") {
                            // check if hpp is enabled if so clear the selected option because you select different payment method
                            if($('adyen_hpp_enable_fields'))
                            {
                                var form = $('adyen_hpp_enable_fields');
                                var elements = form.getElementsByTagName('input');
                                for (var i=0; i<elements.length; i++) elements[i].checked = false;
                            }

                            // don't show the ideal payments as well
                            $('payment_form_ideal').hide();

                        }

                        // check if oneclick is enabled if so clear the selected option because you select different payment method
                        if(method != "adyen_oneclick") {
                            // always enable the oneclick payments options if this payment method is on
                            if($('oneclick_payment_form_adyen_oneclick'))
                            {
                                var form = $('oneclick_payment_form_adyen_oneclick');
                                var elements = form.getElementsByTagName('input');
                                for (var i=0; i<elements.length; i++) elements[i].checked = false;

                                // hide the cvc fields
                                $$('.cvc_block').each(
                                    function (e) {
                                        e.setStyle({display:'none'});
                                    }
                                );
                            }
                        }

                        payment.switchMethod(method);

                        // always enable adyen_hpp
                        if ($('payment_form_adyen_hpp')){
                            var form = $('payment_form_adyen_hpp');
                            form.style.display = '';
                            var elements = form.getElementsByTagName('input');
                            for (var i=0; i<elements.length; i++) elements[i].disabled = false;
                            var elements = form.getElementsByTagName('select');
                            for (var i=0; i<elements.length; i++) elements[i].disabled = false;
                        }
                    };
                    Event.observe($('p_method_<?php echo $_code ?>'), 'change', SwitchMethod);

                    //]]>
                </script>
            <?php endforeach; ?>
        </dl>
    <?php endif;?>
</div>
<script type="text/javascript">
    //<![CDATA[

    $$('.cvv-what-is-this').each(function(element){
        Event.observe(element, 'click', toggleToolTip);
    });

    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                left: (Event.pointerX(event)-100)+'px',
                top: (Event.pointerY(event)-300)+'px'
            });
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }

    var checkout = new Checkout();
    $$('#checkout-payment-method-load dt input').invoke('observe', 'click', function(e) {

        var element = e.element();
        var name = 'payment_form_' + element.getValue();
        payment.currentMethod = element.getValue();
        /* Hide all other forms */
        $$('dd.payment-method').invoke('hide');

        if(element.checked) {
            payment.switchMethod(payment.currentMethod);
            var form = $(name);
            var container = $('container_payment_method_' + element.getValue());

            if(element !== null && container !== null)    {
                container.show();
                $(name).show();
            }
        }
    });

    // ADYEN: set current method as well if you click on hpp and oneclick
    $$('div.payment-methods input[name="payment[hpp_type]"]').invoke('observe', 'click', function(e) {
        payment.currentMethod = "adyen_hpp";
    });

    $$('div.payment-methods input[name="payment[recurring]"]').invoke('observe', 'click', function(e) {
        payment.currentMethod = "adyen_oneclick";
    });

    <?php if(Mage::helper('onestepcheckout')->isEnterprise() && Mage::helper('customer')->isLoggedIn()):?>
    //if we have a enterprise version we should include this

    rPoints = $('use_reward_points');
    if(rPoints){
        if(rPoints.checked){
            payment.switchRewardPointsCheckbox();
        }
    }
    cBalance = $('use_customer_balance');
    if(cBalance){
        if(cBalance.checked){
            payment.switchCustomerBalanceCheckbox();
        }
    }
    //if we have a enterprise version we should include this end
    <?php endif;?>

    payment.switchMethod(payment.currentMethod);


    <?php echo $this->getChildHtml('giftcardaccount_scripts');?>
    //]]>
</script>
